#!/bin/zsh
################################################################################
# Darwin/macOS base system paths
# Adds basic system directories to PATH
################################################################################

addpath /sbin
