#!/bin/zsh
################################################################################
# Go language configuration
# Sets up Go paths and provides go mod tidy utility
################################################################################

[ -z "$GOPATH" ] && export GOPATH=$HOME/.local/go/path
[ -z "$GOROOT" ] && export GOROOT=$HOME/.local/go/root

# Add Go paths if GOROOT exists
[ -d "$GOROOT" ] && addpath $GOROOT/bin
[ -d "$GOPATH/bin" ] && addpath $GOPATH/bin
