#!/bin/zsh
################################################################################
# AWS configuration and utilities
# Provides AWS profile management and eksctl completion
################################################################################

function aws-set-profile() {
  [ -n "$1" ] || {
    unset AWS_PROFILE
    err "AWS Profile set to default. Add profile name to arg for non-default"
    return 0
  }
  export AWS_PROFILE=$1
  err "AWS Profile set to $AWS_PROFILE"
}

# Load eksctl completion if available
if command -v eksctl &>/dev/null; then
  source <(eksctl completion zsh)
fi
