#!/bin/zsh
################################################################################
# ZSH notification plugin for Darwin/macOS iTerm2
# Loads zsh_notify plugin when running in iTerm.app
################################################################################

[[ "$TERM_PROGRAM" == "iTerm.app" ]] && {
  [ -f "${HOME}/.zsh_plugins/zsh_notify.zsh" ] && {
    source "${HOME}/.zsh_plugins/zsh_notify.zsh"
  } || {
    err "WARNING: ${HOME}/.zsh_plugins/zsh_notify.zsh not found. Run install.sh to generate it."
    antidote load ${ZSH_PROFILE}/plugins/zsh_notify
  }
} ||:
