#!/bin/zsh
################################################################################
# Kubernetes kubectl configuration
# Completions managed by gen-completions
################################################################################

alias k=kubectl

# Set up completion for k alias
# We use autoload to defer loading until first use
if (( $+functions[_kubectl] )) || [[ -f "${HOME}/.zsh/completions/_kubectl" ]]; then
  compdef _kubectl k 2>/dev/null || true
fi

function kset() {
  [[ "$1" ]] && {
    k config use-context "$1"
  } || {
    k config get-contexts --output=name
  }
}

function knset() {
  [[ "$1" ]] && {
    k config set-context --current --namespace="$1"
  } || {
    k get ns
  }
}
