#!/bin/zsh
################################################################################
# Custom scripts path
# Adds user scripts directory to PATH
################################################################################

addpath "$ZSH_PROFILE/scripts"
