#!/bin/zsh
################################################################################
# Linux base system paths
# Adds core Linux system directories to PATH
################################################################################

# Linux base paths
# Note: Intentionally using direct PATH modification for base system paths
# This runs early to establish baseline before other modules use addpath
addpath /usr/bin /bin /usr/sbin /sbin /usr/local/bin /usr/local/sbin
