#!/bin/zsh
################################################################################
# Linux grep configuration
# Unsets GREP_OPTIONS for Linux systems
################################################################################

unset GREP_OPTIONS
