#!/bin/zsh
################################################################################
# bat configuration
# Disables pager so bat behaves like cat with syntax highlighting
################################################################################

# Disable pager so bat acts like cat
export BAT_PAGER=""
