#!/bin/zsh
################################################################################
# Java configuration for Darwin/macOS
# Sets JAVA_HOME and adds Java binaries to PATH
################################################################################

export JAVA_HOME="$HOME/.local/jdk/jdk/Contents/Home"
addpath "$JAVA_HOME/bin"

# Add path without using addpath because we want this java to take precedence over /usr/bin/java
# [ -n "$JAVA_HOME" ] && export PATH=$JAVA_HOME/bin:$PATH
