#!/bin/zsh
################################################################################
# Android SDK configuration for Darwin/macOS
# Sets ANDROID_HOME and adds command-line tools and platform-tools to PATH
################################################################################

export ANDROID_HOME="$HOME/.local/android"
addpath "$ANDROID_HOME/cmdline-tools/latest/bin"
addpath "$ANDROID_HOME/platform-tools"
