#!/bin/zsh
################################################################################
# Jenkins path configuration for Darwin/macOS
# Adds Jenkins directory to PATH if installed
################################################################################

[ -d /usr/local/jenkins ] && addpath /usr/local/jenkins
