#!/bin/zsh
################################################################################
# NPM global package path
# Adds NPM global bin directory to PATH
################################################################################

addpath $HOME/.npm-global/bin
