#!/bin/zsh
################################################################################
# direnv configuration
# Auto-loads .envrc files per directory using direnv hook
################################################################################

[ -x /opt/homebrew/bin/direnv ] && {
  eval "$(/opt/homebrew/bin/direnv hook zsh)"
} ||:

# alias cd=z is set after zoxide init in zshrc
