#!/bin/zsh
################################################################################
# Pasteboard clear utility for Darwin/macOS
# Provides function to clear the macOS clipboard
################################################################################

function pbclear() {
  cat /dev/null| pbcopy
  err "pasteboard cleared"
}
