#!/bin/zsh
################################################################################
# Shelly CLI configuration
# Loads shell completion for shelly and sets config path
################################################################################

which shelly > /dev/null 2>&1 || return 0

source <(shelly completion zsh)
export SHELLY_CONFIG=${HOME}/.shelly/shelly.yaml
