#!/bin/zsh
################################################################################
# Homebrew configuration for Linux
# Detects and adds Linuxbrew/Homebrew paths
# Generates brew completion
################################################################################

# Detect Homebrew/Linuxbrew location on Linux
if [ -d /home/linuxbrew/.linuxbrew ]; then
  addpath /home/linuxbrew/.linuxbrew/sbin /home/linuxbrew/.linuxbrew/bin
  HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
elif [ -d $HOME/.linuxbrew ]; then
  addpath $HOME/.linuxbrew/sbin $HOME/.linuxbrew/bin
  HOMEBREW_PREFIX="$HOME/.linuxbrew"
fi

# Homebrew manages its own completions via FPATH
# Ensure brew completions are linked
if [[ -n "$HOMEBREW_PREFIX" ]] && [[ -x "${HOMEBREW_PREFIX}/bin/brew" ]]; then
  # Homebrew adds its completion directory to FPATH automatically
  # Completions are in ${HOMEBREW_PREFIX}/share/zsh/site-functions
  if [[ -d "${HOMEBREW_PREFIX}/share/zsh/site-functions" ]]; then
    fpath=("${HOMEBREW_PREFIX}/share/zsh/site-functions" $fpath)
  fi
fi
